### ISSUE TITLE
Potentially change "state-read" to a more suited name

### ISSUE THREAD

**Issue by mitchmindtree** [essential-contributions/essential-base#172]
The main motivation behind what we currently refer to as "state read" programs is to allow user to prepare a set of arbitrary inputs that can be shared by one or more constraints.

The current name can lead to a bit of confusion, as it implies that all state read programs read from state, or that the resulting state slots contain something that is solely derived from state.

In reality however, the state read program might just do some expensive calculation using purely data whose result must be made available to multiple constraints. In other words, there are reasonable ways to use these programs that have nothing to do with state.

This would require changes to the following:

- [ ] `essential-state-read-vm`
- [ ] `StateReadBytecode`
- [ ] `StateSlot(s)`
- [ ] `essential-state-asm` (maybe)
- [ ] Documentation
- probably more

---

I gave the above text to chatgpt and asked it to spit out a bunch of potential names to kick off bike-shedding:

- Shared Input Program (SIP)
- Common Calculation Program (CCP)
- Global Input Provider (GIP)
- Unified Input Processor (UIP)
- Constraint Input Program (CIP)
- Collective Data Provider (CDP)
- Universal Data Preparer (UDP)
- Computation Input Provider (CIP)
- Global Context Generator (GCG)
- Common Data Preprocessor (CDP)
- Input Prep
- Data Prep
- Input Share
- Calc Share
- Input Pool
- Prep Calc
- Shared Data
- Common Inputs
- Shared Calc
- Data Source
- Preparer
- Unifier
- Provider
- Aggregator
- Collector
- Assembler
- Consolidator
- Synthesizer
- Gatherer
- Merger

I don't mind the "input-prep" or "preprocess" terminology

**Comment by mitchmindtree** [comment]
As of #188, this can now just be `Program`

**Comment by freesig** [comment]
@mitchmindtree Can we close this?

**Comment by supiket** [comment]
Closing due to a larger design change that includes this
