### ISSUE TITLE
Optimisation: Update `essential-check` to only execute "post"-run for state read programs if `Op::StateRead` occurs in "pre"-run

### ISSUE THREAD

**Issue by mitchmindtree** [essential-contributions/essential-base#173]
We can avoid doing the "post-state" execution for a state read program if we know that all of the inputs are the same as the "pre-state" execution.

All inputs to state read execution are known before execution begins *besides* the results of any `Op::StateRead` operations that might occur.

As a result, if pre-state execution never encounters a `Op::StateRead` operation, we know that post-state would result in the exact same result due to referential transparency, so there's no need to perform the post-state execution.

Implementing this requires two steps:

1. Ensure that post-state execution does not have access to the pre-state slots for the current state read program (as this would break referential transparency, and pint cannot output programs capable of this anyway). In other words, just move [this line](https://github.com/essential-contributions/essential-base/blob/c465293ae736cbaa1a330b6cbcad3ee0de105f91/crates/check/src/solution.rs#L528) to after the post-state read.
2. Update the state-read VM to have a `read_state: bool` flag or similar that is set to `true` if/when a `Op::StateRead` is encountered. An alternative would be to track this in the `StateRead` trait implementation, but this kind of muddies the trait a little, and it would need some way of resetting between separate state read programs which feels a bit imperative.

**Comment by freesig** [comment]
@mitchmindtree Can we close this?

**Comment by freesig** [comment]
oh um probably close? Can always reopen but might just make it easier to track what's done
