### ISSUE TITLE
Declarative data sharing

### ISSUE THREAD

**Issue by freesig** [essential-contributions/essential-base#182]
# Proposal
1. Remove pub vars
2. Change `PredicateAt` to `PredicateExists`
3. Potentially change `decision variables` to `predicate arguments`.

We can look at pub vars as a form of message passing between predicates. However this issue proposes a simpler way to achieve the same thing.

## Currently
To share a message between two predicates we might do:
```rust
predicate a {
    pub var msgs MyMsg;
    constraint msgs == //...
}
```
```rust
interface contract_a {
    predicate a {
        pub var msgs: MyMsg;
    }
}

predicate b {
    interface C = contract_a(token.contract_a);
    predicate a = C::a(token.addr);
    constraint a::msgs == //...
}
```
This is awkward because it implies a directionality to the data as if it's coming from `a` but it's not. The message is the aggregation of all messages shared between the predicates within the atomic time step.

## Declarative messaging
The idea here is to say:
> There `exists` some `other` predicate who's argument is the same `msgs` as my argument.

```rust
predicate a(msgs: MyMsg, other: Predicate) {
	constraint other(msgs, __this_address()) && msgs[0] >= 43;
}

predicate b(msgs: MyMsg, other: Predicate) {
	constraint other(msgs, __this_address()) && msgs[1] <= 101;
}
```

```rust
// other(msgs, __this_address()) becomes 
 constraint __predicate_exists(hash(msgs, __this_address()) == other.address
```
The solution would look like:
```rust
let msgs = vec![...];
let a_addr = //...
let b_addr = //...

let solution_a = Solution {
	solves: a_addr,
	args: vec![msgs, b_addr]
}

let solution_b = Solution {
	solves: b_addr,
	args: vec![msgs, a_addr]
}
```
The opcode to allow this would be something like:
```yaml
PredicateExists:
  stack_in: [hash(args...)],
  stack_out: [predicate_address]
```

# Advantages
- Don't need to pass in pathway anymore.
- It's much simpler and more intuitive.
- Can message pass declarative.
- No extra data as it's de-duped either by compression or a compressed solution format.

# Partial Predicate Exists (optional)
If we wanted the ability to only check that there is a predicate who has some subset of arguments we could also introduce:
```yaml
PartialPredicateExists:
  stack_in: [bitflags_of_args, hash(args...)],
  stack_out: [predicate_address]
```

**Comment by mohammadfawaz** [comment]
```rust
interface Baz {
    predicate Foo {
        pub var x: int;
        pub var q: b256;
    }

    predicate Bar {
        pub var w: int;
        pub var p: int;
    }
}

predicate Simple {
    var foo_addr = 0x0000000000000000000000000000000000000000000000000000000000000000;
    var bar_addr = 0x0000000000000000000000000000000000000000000000000000000000001111;

    interface BazInstance = Baz(0xEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEE);
    predicate FooInstance1 = BazInstance::Foo(foo_addr);

    var x = FooInstance1::x;
    constraint FooInstance1::q == 0x0000000000000001000000000000000100000000000000010000000000000001;

    predicate FooInstance2 = BazInstance::Foo(foo_addr);
    constraint FooInstance2::x == 2898;
    constraint FooInstance2::q == 0x0000000000000003000000000000000300000000000000030000000000000003;

    predicate BarInstance = BazInstance::Bar(bar_addr);
    constraint BarInstance::w == 42;
    constraint BarInstance::p == 43;
}
```

**Comment by freesig** [comment]
Should be something like this:
```rust
use baz;

const Q = 0x0000000000000001000000000000000100000000000000010000000000000001;

predicate simple(x: int) {
 
    // Interface instance
    interface BazInstance = Baz();

    // First instance of predicate `foo`
    constraint bar::foo(x, Q);

	// Above is sugar for:
    // constraint __preadicate_exists(hash(x, Q)) == { contract_addr: baz::CONTRACT_ADDR, predicate_addr: baz::foo::PREDICATE_ADDR };


    // Second instance of predicate `foo`
    constraint bar::foo(2898, 0x0000000000000003000000000000000300000000000000030000000000000003);

	// Above is sugar for:
    // constraint __preadicate_exists(hash(2898, 0x0000000000000003000000000000000300000000000000030000000000000003)) == { contract_addr: baz::CONTRACT_ADDR, predicate_addr: baz::foo::PREDICATE_ADDR };

    // One instance of predicate `bar`
    constraint baz::bar(42, 43);

	// Above is sugar for:
    // constraint __preadicate_exists(hash(42, 43)) == { contract_addr: baz::CONTRACT_ADDR, predicate_addr: baz::bar::PREDICATE_ADDR };
}
```

**Comment by mohammadfawaz** [comment]
What if instead of 
```
    constraint FooInstance2::x == 2898;
```
I had 
```
    constraint FooInstance2::x * FooInstance2::x < 10;
```
That is, what if I want to constrain the pub vars of another predicate in arbitrary ways?

**Comment by freesig** [comment]
You mean like?
```rust
constraint baz::foo(x * x) && x * x < 10;
```

**Comment by mohammadfawaz** [comment]
Brain dump from Slack:

![image](https://github.com/user-attachments/assets/c255c4a1-4f6e-4535-a7c3-d96a6bf4ffa6)

Here’s an attempt at the new design for sharing data between predicates. On the left is the old design where each predicate interface auto-generates a decision variable for the pathway. On the right is the corresponding new approach which is similar to what’s been proposed. This seems like the least invasive change:
1. no more `pub var` and all vars are arguments.
2. Predicate still live in `interface` and must contain all the vars in the predicate. The vars are basically args. Recall that the `interface` can be auto-generated from the corresponding (external) contract.
3. `interface` instance and `predicate` instances remain the same. You still need predicate instances to specify their address, but no auto-generation of decision variables for pathway here.
4. I’m now happy with writing constraint `BarInstance1(x1, x2, x3);` to say: “The predicate instance BarInstance, called with `y1, y2, y3` must be satisfied”. This means: the solution must have a corresponding “solution data” AND the predicate must result in `true` , i.e., all of its constraints are satisfied. Semantically, we could say that “calling” a predicate like that always returns a `bool` that indicates whether the predicate is satisfied, with the given inputs, or not. Note that the signature must match what’s in the interface or else we get a compile error.

You could also imagine a shortcut like this, which skips the predicate instances:

```rust
    interface FooInstance = Foo(addr1);
    
    constraint FooInstance::Bar(addr2)(y1, y2, y3);
    constraint FooInstance::Bar(addr3)(z1, z2, z3);
```

but that’s a little weird...

And as I said, this is not too invasive. It wouldn’t take us a long time to make this work. In fact, we would delete a lot of code since (I assume) everything to do with “transient” data will go away including the opcodes etc. 

Oh, and as a byproduct of all of this, the ABI will now “match” the `interface`. The ABI can actually be completely generated from the `interface`. Previously that wasn’t possible because interfaces didn’t have private vars but the ABI did. Now, they contain the same information: `storage` vars and `predicate` args.

This also presents an opportunity for us to write code like this:

```rust
constraint SomePredicateInstance(...) || SomeOtherPredicateInstance(...);
```

which is something that @simonr0204 and I discussed before but in a different way. This says “I want at least one of those two external predicates to be satisfied” (e.g. interacting with multiple DEXs), which means one of them could be false which is not how the VM works today since it requires all the “solved” predicates to be fully satisfied (i.e. evaluate to `true`). This presents some challenges though because we still need to say that the “top level predicate” (predicate `Simple` in the example above) is satisfied which means we need the concept of “top level predicates”, and that’s quite annoying.

**Comment by freesig** [comment]
> Semantically, we could say that “calling” a predicate like that always returns a bool that indicates whether the predicate is satisfied

I think this is wrong and an important distinction. The bool returned is true if the other predicate exists with the given args. That bool says nothing about whether or not the other predicate was solved to true. This is important because we are not waiting for the other predicate to be checked. We are not waiting for a result. We just know that all predicates that are solved in the same solution are AND together and the entire solution must be true.

**Comment by freesig** [comment]
> which means one of them could be false which is not how the VM works today since it requires all the “solved” predicates to be fully satisfied (i.e. evaluate to true). This presents some challenges though because we still need to say that the “top level predicate” (predicate Simple in the example above) is satisfied which means we need the concept of “top level predicates”, and that’s quite annoying

I think there's a misconception here based on the above comment. The OR here is over the solutions to the predicates existing or not. Not over their outcomes. This is possible with the proposed changes to PredicateExists.
There's no need for a top level predicate because the dependency is one of exists. They can be solved in any order.

**Comment by mohammadfawaz** [comment]
Yeah this makes sense. I went off script for a bit looking for ways to make this more interesting, but I guess there are downsides. 

Either way, I think the synatx
```rust
constraint SomePredicateInstance(...) || SomeOtherPredicateInstance(...);
```
to mean either predicate exist in the solution is fine. I think it still serves the same purpose as what I'm thinking of (interacting with one of many DEXs etc.) where the solver is free to pick one of the predicates to solve and not necessarily both.

Besides that, is everything else, syntax-wise reasonable?

**Comment by mohammadfawaz** [comment]
> This is important because we are not waiting for the other predicate to be checked.

Yeah this is a very good point.

**Comment by mohammadfawaz** [comment]
Also cc @otrho. If we're on board with the syntax and the semantics, I can start experimenting with this tomorrow. Ideally the next hackathon would use the new syntax.

**Comment by freesig** [comment]
The only thing that comes to mind is it could be good to have a shortcut constructor for when you only want to call a single predicate like:
```rust
predicate bar = FooBar(full_predicate_addr);
constraint bar(arg);
```
Just because this is likely the most common case

**Comment by otrho** [comment]
> > This is important because we are not waiting for the other predicate to be checked.
>
> Yeah this is a very good point.

Except semantically there's no difference.  There is no 'waiting' because there's no control flow.  All these predicates must be solved by the same solution (right?) so a predicate confirming that another predicate is passed specific data _is_ a logical dependency.

So IMO using the rhetoric that `constraint other_predicate(blah);` is a 'call' and it returns bool is not harmful (although 'call' implies control flow) and is a more natural way to think about the relationship.

**Comment by otrho** [comment]
`constraint FooInstance::Bar(addr2)(y1, y2, y3);` isn't that weird if we make the `FooInstance::Bar(addr2)` a (compile time) expression.  But then syntactically that currently looks like a union variant.

`constraint FooInstance::Bar(addr2, y1, y2, y3);` or `constraint FooInstance::Bar(|addr2| y1, y2, y3);` or some other syntactic thing might work.

Or just use a macro `@instance(FooInstance::Bar(addr2); y1; y2; y3)`.

**Comment by freesig** [comment]
> So IMO using the rhetoric that constraint other_predicate(blah); is a 'call' and it returns bool is not harmful (although 'call' implies control flow) and is a more natural way to think about the relationship.

I just think it's important to state what the bool actually represents. If the other predicate does exist in the solution with those args but returns false this bool will still be true.

**Comment by freesig** [comment]
@mohammadfawaz would you like me to add the PredicateExists op so you can experiment?

**Comment by mohammadfawaz** [comment]
> @mohammadfawaz would you like me to add the PredicateExists op so you can experiment?

Yes please!

> isn't that weird if we make the `FooInstance::Bar(addr2)` a (compile time) expression. But then syntactically that currently looks like a union variant.

I suppose that's true and having a separate `predicate` declaration is slightly unnecessary if we can just go straight from the interface instance. Your suggestions are good. I'll think on some more.

> The only thing that comes to mind is it could be good to have a shortcut constructor for when you only want to call a single

That's also a valid point. We should be able to invoke a predicate directly with a single line.

> I just think it's important to state what the bool actually represents. 

What Toby and I are hinting at is to actually **change** what the `bool` means, but I understand that if we do this, then we lose the ability to check predicates independently (i.e. in parallel) in a given solution.

**Comment by freesig** [comment]
>What Toby and I are hinting at is to actually change what the bool means, but I understand that if we do this, then we lose the ability to check predicates independently (i.e. in parallel) in a given solution.

Yeh we definitely don't want to change what that bool means. That's very important. Otherwise we can end up with deadlocks and all sorts of dependency problems.

**Comment by otrho** [comment]
> > So IMO using the rhetoric that constraint other_predicate(blah); is a 'call' and it returns bool is not harmful (although 'call' implies control flow) and is a more natural way to think about the relationship.
> 
> I just think it's important to state what the bool actually represents. If the other predicate does exist in the solution with those args but returns false this bool will still be true.

But if the predicate fails then the solution fails, so the bool also means 'this predicate with these args must pass'.

So yeah, I guess it depends on how you constrain it.  `constraint pred(a);` is 'this exists' and is also 'this must pass'.  `constraint !pred(a);` is saying it mustn't exist, and therefore can't pass, which still fits the 'call' paradigm.

I still don't see the ambiguity and the fact that the bool can be true while the predicate fails is just an implementation detail and not useful to the Pint dev.

**Comment by freesig** [comment]
@mohammadfawaz https://github.com/essential-contributions/essential-base/pull/186

**Comment by freesig** [comment]
> I still don't see the ambiguity and the fact that the bool can be true while the predicate fails is just an implementation detail and not useful to the Pint dev.

If the bool had to be the result of the other predicate then how would we know what to set it to without first checking the other predicate?

**Comment by freesig** [comment]
@otrho Are you saying we return if it exists but as a pint dev I can think of it as the result because overall the solution will fail anyway?

**Comment by otrho** [comment]
> @otrho Are you saying we return if it exists but as a pint dev I can think of it as the result because overall the solution will fail anyway?

Yes?  I don't think the distinction is important and it's more natural to think of the dependency as existential for the solution.

**Comment by mohammadfawaz** [comment]
> `constraint !pred(a);` is saying it mustn't exist, and therefore can't pass

This is the only tiny point of confusing. Someone _might_ think that they can provide a bad solution to `pred(a)` and expect this constraint to be satisfied... This, of course, goes against the higher principle that ALL predicates in a solution must be satisfied. Either way, we need to be clear in the docs.

**Comment by freesig** [comment]
Yeh `!pred(a)` is interesting. If you interpret it as exists then it makes perfect sense. This other predicate can't exist with these parameters.
If you interpret it as a result then it's saying the other predicate must exist but also must return false which would cause the whole solution to be false.
Basically ` constraint !__pred_exists(a)` can evaluate to true and the entire solution can be valid. `constraint !__eval_pred(a)` if true would never allow the entire solution to be valid.
I think they are semantically different in this way.
Maybe function call syntax is not the best choice because it might mislead devs into thinking it's more like eval?

**Comment by otrho** [comment]
> Basically ` constraint !__pred_exists(a)` can evaluate to true and the entire solution can be valid. `constraint !__eval_pred(a)` if true would never allow the entire solution to be valid.
> I think they are semantically different in this way.

I still disagree.  From the point of view of a Pint developer they're the same, unless as @mohammadfawaz points out, they're under the illusion that it's possible for *some* predicates in a solution to fail.  This is the only thing that needs elucidating.

**Comment by freesig** [comment]
I think if `eval(p)` returns `false` when `p` isn't in the solution then you have a point. They are equivalent.
Because if `p` was in the solution and returned false then `solution == false` anyway.
So yeh it's almost like an optimistic "if `p` in solution then assume it evaluates to `true` because if it doesn't then nothing does".

We just need to be clear that we can't ever have something like:
```rust
constraint p(12) == 42;
```
We don't want to or need to ever introduce that as there are better ways to achieve exactly the same thing.

**Comment by freesig** [comment]
And I think this is a fair assumption because you're evaluating a predicate not a program and predicates only ever return a bool

**Comment by freesig** [comment]
Closing this as it's now complete. Opened #222 for partial args
