### ISSUE TITLE
essential-check DAG execution

### ISSUE THREAD

**Issue by freesig** [essential-contributions/essential-base#202]
_from @mitchmindtree_

Currently in `essential_check::solution::check_predicate`, we first run all the state read programs to accumulate the state slots, then we run the constraint programs.

Now that we're [generalising the predicate's program graph](https://github.com/essential-contributions/essential-base/issues/188), we want to execute *all* programs in one traversal in order of dependency.

As a `Predicate`'s programs will be required to be in a topological ordering upon deployment (see #194), we can simply evaluate the nodes in order, each on their own task, using tokio oneshot channels to provide the results of parents to their children.

See the WIP at #199.

**Comment by freesig** [comment]
@mitchmindtree maybe you can fill this issue out as I'm not sure exactly what your plan is?

**Comment by mitchmindtree** [comment]
Closed via #199, which will land as a part of #212.
